---
jobs:
  - <<: (( merge )) # Pull other jobs from previous stubs
  - name: cloud_controller
    templates:
      - name: cloud_controller_ng
    instances: 1
    resource_pool: common
    networks:
      - name: outbound
        default: [dns, gateway]
    properties:
      ccdb: ccdb
      networks:
        apps: outbound

  - name: cloud_controller_worker
    templates:
      - name: cloud_controller_worker
    instances: 1
    resource_pool: common
    networks:
      - name: outbound
        default: [dns, gateway]
    properties:
      ccdb: ccdb
      networks:
        apps: outbound

