---
jobs:
  - <<: (( merge )) # Pull other jobs from previous stubs
  - name: health_manager
    templates:
      - name: hm9000
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

