---
job_address: (( merge )) # Just an include

jobs:
  - <<: (( merge )) # Pull other jobs from previous stubs
  - name: loggregator
    templates:
      - name: loggregator
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

properties:
  <<: (( merge ))
  syslog_aggregator:
    address: (( job_address.syslog_aggregator.address ))
    port: 54321
