---
jobs:
  - <<: (( merge )) # Pull other jobs from previous stubs
  - name: loggregator
    templates:
      - name: loggregator
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

