---
jobs:
  - <<: (( merge )) # Pull other jobs from previous stubs
  - name: runner
    templates:
      - name: dea_next
      - name: dea_logging_agent
      - name: metron_agent
    instances: 3
    resource_pool: large
    networks:
      - name: default
        default: [dns, gateway]
    update:
      max_in_flight: 1

