---
jobs:
  - <<: (( merge )) # Pull other jobs from previous stubs
  - name: uaa
    templates:
      - name: uaa
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

