---
terraform_outputs: (( merge ))

networks:
  - name: default
    type: dynamic
    cloud_properties:
      network_name: (( terraform_outputs.gce.network_name ))
      ephemeral_external_ip: true
      tags:
        - bosh
        - cfmichael-update-me
  - name: static
    type: vip

resource_pools:
  - name: common
    network: default
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 40
      root_disk_type: pd-standard
  - name: large
    network: default
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      machine_type:  n1-highmem-8
      root_disk_size_gb: 40
      root_disk_type: pd-standard

disk_pools:
  - name: data
    disk_size: 40_960
    cloud_properties:
      type: pd-ssd

  - name: core
    disk_size: 10_024
    cloud_properties:
      type: pd-ssd

jobs:
  - name: haproxy
    templates:
      - name: haproxy
      - name: consul_agent
      - name: metron_agent
    instances: 1
    resource_pool: large
    networks:
      - name: default
        default: [dns, gateway]
      - name: static
        static_ips:
          - 104.155.70.65

  - name: data
    templates:
      - name: debian_nfs_server
      - name: postgres
      - name: metron_agent
    instances: 1
    resource_pool: common
    persistent_disk_pool: data
    networks:
      - name: default
        default: [dns, gateway]

  - name: core
    templates:
      - name: nats
      - name: nats_stream_forwarder
      - name: etcd
      - name: etcd_metrics_server
      - name: hm9000
      - name: uaa
      - name: login
      - name: metron_agent
    instances: 1
    resource_pool: common
    persistent_disk_pool: core
    networks:
      - name: default
        default: [dns, gateway]

  - name: api
    templates:
      - name: gorouter
      - name: routing-api
      - name: cloud_controller_ng
      - name: cloud_controller_clock
      - name: cloud_controller_worker
      - name: consul_agent
      - name: doppler
      - name: loggregator_trafficcontroller
      - name: syslog_drain_binder
      - name: metron_agent
      - name: nfs_mounter
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

  - name: runner
    templates:
      - name: dea_next
      - name: dea_logging_agent
      - name: metron_agent
    instances: 3
    resource_pool: large
    networks:
      - name: default
        default: [dns, gateway]
    update:
      max_in_flight: 1

properties: {}
