---
job_address: (( merge )) # Simple include
secrets: (( merge )) # Simple include

jobs:
  - <<: (( merge )) # Pull other jobs from previous stubs
  - name: nats
    templates:
      - name: nats
      - name: nats_stream_forwarder
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

properties:
  <<: (( merge ))
  nats:
    user: nats
    password: (( secrets.passwords.cf.nats ))
    address: (( job_address.nats.address ))
    port: 4222
    machines:
      - (( job_address.nats.address ))
